server:
  servlet:
    # 设置全局API前缀
    context-path: /fly

spring:
  profiles:
    # 激活开发环境 dev  生产环境 pro
    active: dev
  main:
    banner-mode: off


  jackson:
    serialization:
      write-dates-as-timestamps: true # date 转时间戳
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
